### ISSUE TITLE
Error while logging into Consent UI

### ISSUE THREAD

**Issue by profisysitsolutions** [sdhealthconnect/leap-cds#128]
![Error_Consent_UI](https://user-images.githubusercontent.com/74448849/144197915-109cc535-fba3-4ff4-b707-d47f2333f352.JPG)

**Comment by ddecouteau** [comment]
This issue should be logged  in leap-consent-ui project.

You probably need to provision/map the users to their respective FHIR patient resources.

For setup and testing purposes we just used liquidbase to perform this task.

Perform following.
1) under resources/db/data create new versions of link_consent_user_v#.csv and consentuser_new_fhir_ids_v#.csv 
with their associated FHIR Patient/id 

2) under resource/db/changelog update the changelog.xml file adding a new changeSet use changeSet id "00000000000007" as example.

Rebuild and deploy

**Comment by ddecouteau** [comment]
Closing this issue, further discussion should be done within Leap-consent-ui project
