### ISSUE TITLE
Add CDS Hook discovery endpoint

### ISSUE THREAD

**Issue by mojitoj** [sdhealthconnect/leap-cds#7]
The client must be able to discover the CDS hook on this server and its specifications via the service discovery endpoint as defined by the CDS Hooks specs.

**Comment by buserr0r** [comment]
I put together a first pass at this based on the way it is implemented in [cds sandbox](https://github.com/cds-hooks/sandbox-cds-services). If you are interested in taking a look I can open a PR.
